annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/changes: |
    - kind: changed
      description: upgrade app version to 0.13.3
      links:
        - name: Ollama release v0.13.3
          url: https://github.com/ollama/ollama/releases/tag/v0.13.3
    - kind: added
      description: add ipFamilies and ipFamilyPolicy to the service
      links:
        - name: PR#207
          url: https://github.com/otwld/ollama-helm/pull/207
apiVersion: v2
appVersion: 0.13.3
description: Get up and running with large language models locally.
home: https://ollama.ai/
icon: https://ollama.ai/public/ollama.png
keywords:
- ai
- llm
- llama
- mistral
kubeVersion: ^1.16.0-0
maintainers:
- email: contact@otwld.com
  name: OTWLD
name: ollama
sources:
- https://github.com/ollama/ollama
- https://github.com/otwld/ollama-helm
type: application
version: 1.36.0
