# MetalLB L2Advertisement: advertise jyje-pool via L2 (ARP/NDP).
# See: https://metallb.io/configuration/#layer-2-configuration
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertise-all-pools
  namespace: metallb-system
spec:
  ipAddressPools:
    - default-addresspool
