annotations:
  licenses: MIT
apiVersion: v2
appVersion: 0.5.2
dependencies:
- condition: ollama.enabled
  import-values:
  - child: service
    parent: ollama.service
  name: ollama
  repository: https://otwld.github.io/ollama-helm/
  version: '>=0.24.0'
- condition: pipelines.enabled
  import-values:
  - child: service
    parent: pipelines.service
  name: pipelines
  repository: https://helm.openwebui.com
  version: '>=0.0.1'
- condition: tika.enabled
  name: tika
  repository: https://apache.jfrog.io/artifactory/tika
  version: '>=2.9.0'
description: "Open WebUI: A User-Friendly Web Interface for Chat Interactions \U0001F44B"
home: https://www.openwebui.com/
icon: https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
keywords:
- llm
- chat
- web-ui
name: open-webui
sources:
- https://github.com/open-webui/helm-charts
- https://github.com/open-webui/open-webui/pkgs/container/open-webui
- https://github.com/otwld/ollama-helm/
- https://hub.docker.com/r/ollama/ollama
version: 5.1.0
