annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Changed the ingress logic to allow different types of pathType in place of the hardcoded 'pathType: Prefix'"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.122.4
dependencies:
- condition: valkey.enabled
  name: valkey
  repository: https://valkey.io/valkey-helm/
  version: 0.8.1
description: Helm Chart for deploying n8n on Kubernetes, a fair-code workflow automation
  platform with native AI capabilities for technical teams. Easily automate tasks
  across different services.
home: https://github.com/8gears/n8n-helm-chart
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
- Workflow Automation
- Workflow
- iPaaS
- integration-framework
- low-code-plattform
- low-code
maintainers:
- email: contact@8gears.com
  name: 8gears
  url: https://github.com/8gears
- email: _@8gears.com
  name: n8n
  url: https://github.com/n8n-io
name: n8n
sources:
- https://github.com/n8n-io/n8n
- https://n8n.io/
type: application
version: 2.0.1
