{{- $fullname := include "valkey.fullname" . }}
{{- $storage := .Values.dataStorage }}
{{- $createPVC := and $storage.enabled (not (empty $storage.requestedSize)) (empty $storage.persistentVolumeClaimName) }}
{{- include "valkey.validateAuthConfig" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  selector:
    matchLabels:
      {{- include "valkey.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "valkey.selectorLabels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/initconfig: {{ include (print $.Template.BasePath "/init_config.yaml") . | sha256sum | trunc 32 }}
        {{- if .Values.valkeyConfig }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 32 }}
        {{- end }}
    spec:
      {{ (include "valkey.imagePullSecrets" .) | nindent 6 }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      serviceAccountName: {{ include "valkey.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ include "valkey.fullname" . }}-init
          image: {{ include "valkey.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: [ "/scripts/init.sh" ]
          volumeMounts:
            - name: {{ .Values.dataStorage.volumeName }}
              mountPath: /data
              {{- if .Values.dataStorage.subPath }}
              subPath: {{ .Values.dataStorage.subPath }}
              {{- end }}
            - name: scripts
              mountPath: /scripts
            {{- if .Values.valkeyConfig }}
            - name: valkey-config
              mountPath: /usr/local/etc/valkey/valkey.conf
              subPath: valkey.conf
            {{- end }}
            {{- if .Values.extraSecretValkeyConfigs }}
            - name: extravalkeyconfigs-volume
              mountPath: /extravalkeyconfigs
            {{- end }}
            {{- if .Values.auth.enabled }}
            - name: valkey-acl
              mountPath: /etc/valkey
            {{- if .Values.auth.usersExistingSecret }}
            - name: valkey-users-secret
              mountPath: /valkey-users-secret
              readOnly: true
            {{- end }}
            {{- if or (include "valkey.hasInlinePasswords" . | eq "true") .Values.auth.aclConfig }}
            - name: valkey-auth-secret
              mountPath: /valkey-auth-secret
              readOnly: true
            {{- end }}
            {{- end }}
          {{- with .Values.initResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraInitContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "valkey.fullname" . }}
          image: {{ include "valkey.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "valkey-server" ]
          args: [ "/data/conf/valkey.conf" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
            - name: VALKEY_LOGLEVEL
              value: "{{ .Values.valkeyLogLevel }}"
          ports:
            - name: tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          startupProbe:
            exec:
              {{- if .Values.tls.enabled }}
              command: [ "sh", "-c", "valkey-cli --cacert /tls/{{ .Values.tls.caPublicKey }} --tls ping" ]
              {{- else }}
              command: [ "sh", "-c", "valkey-cli ping" ]
              {{- end }}
          livenessProbe:
            exec:
              {{- if .Values.tls.enabled }}
              command: [ "sh", "-c", "valkey-cli --cacert /tls/{{ .Values.tls.caPublicKey }} --tls ping" ]
              {{- else }}
              command: [ "sh", "-c", "valkey-cli ping" ]
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.dataStorage.volumeName }}
              mountPath: /data
              {{- if .Values.dataStorage.subPath }}
              subPath: {{ .Values.dataStorage.subPath }}
              {{- end }}
            {{- if .Values.tls.enabled }}
            - name: {{ include "valkey.fullname" . }}-tls
              mountPath: /tls
            {{- end }}
            {{- if .Values.auth.enabled }}
            - name: valkey-acl
              mountPath: /etc/valkey
            {{- end }}
            {{- range $secret := .Values.extraValkeySecrets }}
            - name: {{ $secret.name }}-valkey
              mountPath: {{ $secret.mountPath }}
            {{- end }}
            {{- range $config := .Values.extraValkeyConfigs }}
            - name: {{ $config.name }}-valkey
              mountPath: {{ $config.mountPath }}
            {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: {{ include "valkey.metrics.exporter.image" . }}
          imagePullPolicy: {{ .Values.metrics.exporter.image.pullPolicy | quote }}
          {{- with .Values.metrics.exporter.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.metrics.exporter.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.metrics.exporter.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.exporter.port }}
          startupProbe:
            tcpSocket:
              port: metrics
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          {{- with .Values.metrics.exporter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.metrics.exporter.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: REDIS_ALIAS
              value: {{ include "valkey.fullname" . }}
            {{- range $key, $val := .Values.metrics.exporter.extraEnvs }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
        {{- end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "valkey.fullname" . }}-init-scripts
            defaultMode: 0555
        {{- if .Values.auth.enabled }}
        - name: valkey-acl
          emptyDir:
            medium: Memory
        {{- end }}
        {{- if .Values.valkeyConfig }}
        - name: valkey-config
          configMap:
            name: {{ include "valkey.fullname" . }}-config
        {{- end }}
        {{- range .Values.extraValkeySecrets }}
        - name: {{ .name }}-valkey
          secret:
            secretName: {{ .name }}
            defaultMode: {{ .defaultMode | default 0440 }}
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: {{ include "valkey.fullname" . }}-tls
          secret:
            secretName: {{ required "An existing secret is required to enable TLS" .Values.tls.existingSecret }}
            defaultMode: 0400
        {{- end }}
        {{- range .Values.extraValkeyConfigs }}
        - name: {{ .name }}-valkey
          configMap:
            name: {{ .name }}
            defaultMode: {{ .defaultMode | default 0440 }}
        {{- end }}
        {{- if .Values.metrics.enabled }}
        {{- range .Values.metrics.exporter.extraExporterSecrets }}
        - name: {{ .name }}-exporter
          secret:
            secretName: {{ .name }}
            defaultMode: {{ .defaultMode | default 0440 }}
        {{- end }}
        {{- end }}
        {{- if .Values.auth.enabled }}
        {{- if .Values.auth.usersExistingSecret }}
        - name: valkey-users-secret
          secret:
            secretName: {{ .Values.auth.usersExistingSecret }}
            defaultMode: 0400
        {{- end }}
        {{- if or (include "valkey.hasInlinePasswords" . | eq "true") .Values.auth.aclConfig }}
        - name: valkey-auth-secret
          secret:
            secretName: {{ include "valkey.fullname" . }}-auth
            defaultMode: 0400
        {{- end }}
        {{- end }}
        - name: {{ $storage.volumeName }}
        {{- if $storage.persistentVolumeClaimName }}
          persistentVolumeClaim:
            claimName: {{ $storage.persistentVolumeClaimName }}
        {{- else if $createPVC }}
          persistentVolumeClaim:
            claimName: {{ include "valkey.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
