{{- if .Values.auth.enabled }}
{{- if or (include "valkey.hasInlinePasswords" . | eq "true") .Values.auth.aclConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}-auth
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $username, $user := .Values.auth.aclUsers }}
    {{- if $user.password }}
  {{ $username }}-password: {{ $user.password | b64enc }}
    {{- end }}
  {{- end }}
  {{- if .Values.auth.aclConfig }}
  aclConfig: {{ .Values.auth.aclConfig | b64enc }}
  {{- end }}
{{- end }}
{{- end }}